name: Deploy to EC2 (Debian 12 via SSH + Git)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo -e "Host *\n  IdentityFile ~/.ssh/id_rsa\n  IdentitiesOnly yes" >> ~/.ssh/config

      - name: Deploy via SSH and Git
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            TMP_DIR="/tmp/deploy_$(date +%s)"
            mkdir -p "$TMP_DIR"
            cd "$TMP_DIR"

            git clone https://github.com/${{ github.repository }} .

            test -f index.html || { echo "index.html not found"; exit 1; }

            sudo cp index.html /var/www/html/index.html
            sudo cp -rf gifs /var/www/html

            sudo chown www-data:www-data /var/www/html/index.html

            cd /
            rm -rf "$TMP_DIR"

            sudo nginx -s reload
          EOF
